
TYPE
	ST_Output : 	STRUCT 
		PWM_PERIOD : UINT;
		BELT_START : BOOL; (*I1*)
		BELT_DIR : BOOL; (*I2*)
		BELT_CONST_SPEED : BOOL; (*I5*)
		_BELT_DEACC_ : INT; (*I4*)
		_BELT_ACC_ : INT; (*I3*)
		ROBOT_RUN_PRG : BOOL;
	END_STRUCT;
	ST_Input : 	STRUCT 
		Distance : INT; (*Distance sensor on the bottom of the track*)
		ROBOT_READY : BOOL;
	END_STRUCT;
	packML : 
		(
		EXECUTE,
		COMPLETING,
		COMPLETED,
		RESETTING,
		ABORTING,
		ABORTED,
		CLEARING,
		STOPPING,
		STOPPED,
		SUSPENDING,
		SUSPENDED,
		UNSUSPENDING,
		UNHOLDING,
		HELD,
		HOLDING,
		STARTING,
		IDLE
		);
END_TYPE
